name: Python 3.9, Keras 2.10
on:
  workflow_dispatch: # Allow manual triggers
  pull_request:
    branches:
      - main


jobs:
  run-tests:
    uses: ./.github/workflows/run_keras_tests.yml
    with:
      python-version: "3.9"
      tf-version: "2.10.*"